- alias: All Home
  trigger:
    platform: template
    value_template: "{% if is_state('device_tracker.davidsiphonex', 'home') or is_state('device_tracker.sarahsiphone', 'home') %}true{% endif %}"
  action:
    - service: script.blink_disarm

- alias: All Away
  trigger:
    platform: template
    value_template: "{% if not is_state('device_tracker.davidsiphonex', 'home') and not is_state('device_tracker.sarahsiphone', 'home') %}true{% endif %}"
  action:
    - service: notify.ios_davids_iphone_x
      data:
        title: "Bye Felicia"
        message: "We all gone."
    - service: script.blink_arm

- alias: Foyer Motion Detected
  trigger:
    platform: event
    event_type: foyer_motion_detected
  action:
    - service: notify.ios_davids_iphone_x
      data:
        title: "Foyer Motion Detected"
        message: "I've seen some shit."
    - service: script.blink_capture

# - alias: Regularly update Foyer picture
#   trigger:
#     platform: time
#     minutes: "/5"
#   action:
#     - service: script.blink_capture
