- id: letsencrypt-renewal
  alias: LetsEncrypt renewal
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: hassio.addon_stop
    data:
      addon: core_nginx_proxy
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
  - delay: 00:01:30
  - service: hassio.addon_start
    data:
      addon: core_nginx_proxy
- id: '1641092271455'
  alias: Sync Deck Lights
  description: ''
  use_blueprint:
    path: adchevrier/synchronize-the-on-off-state-of-2-entities.yaml
    input:
      entity_1: switch.deck_light
      entity_2: switch.deck_string_lights
- id: '1643764828147'
  alias: Downstairs time schedule - AM
  description: ''
  use_blueprint:
    path: EPMatt/on_off_schedule_state_persistence.yaml
    input:
      automation_target:
        entity_id:
        - light.sconces
        - light.lamps
        - switch.circadian_lighting_downstairs
      on_time: 06:00:00
      off_time: 09:30:00
      trigger_at_homeassistant_startup: true
      custom_trigger_event: s
- id: '1656444036964'
  alias: Daytime Power Outage
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.generator_power_outage
    from: 'false'
    to: 'true'
  condition:
  - condition: or
    conditions:
    - condition: time
      before: '19:00:00'
      after: 08:00:00
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
    - condition: and
      conditions:
      - type: is_not_occupied
        condition: device
        device_id: fb3f16cafb19fcb4fa962d5e921c6df2
        entity_id: binary_sensor.downstairs_occupancy
        domain: binary_sensor
      - type: is_not_occupied
        condition: device
        device_id: e46e919da6b49d895b1900a7b140be90
        entity_id: binary_sensor.upstairs_occupancy
        domain: binary_sensor
      - type: is_not_occupied
        condition: device
        device_id: e52f1373f5b572bff91c6742f52b470e
        entity_id: binary_sensor.basement_occupancy
        domain: binary_sensor
      - type: is_not_occupied
        condition: device
        device_id: 216957fddab350586feab9357425ce0a
        entity_id: binary_sensor.jacobs_room_occupancy
        domain: binary_sensor
    - condition: device
      device_id: fb3f16cafb19fcb4fa962d5e921c6df2
      domain: climate
      entity_id: climate.downstairs
      type: is_preset_mode
      preset_mode: Away
    - condition: device
      device_id: e46e919da6b49d895b1900a7b140be90
      domain: climate
      entity_id: climate.upstairs
      type: is_preset_mode
      preset_mode: Away
  action:
  - device_id: fb3f16cafb19fcb4fa962d5e921c6df2
    domain: climate
    entity_id: climate.downstairs
    type: set_preset_mode
    preset_mode: Away
  - device_id: e46e919da6b49d895b1900a7b140be90
    domain: climate
    entity_id: climate.upstairs
    type: set_preset_mode
    preset_mode: Away
  mode: single
- id: '1659480564190'
  alias: Downstairs time schedule - PM
  description: ''
  use_blueprint:
    path: EPMatt/on_off_schedule_state_persistence.yaml
    input:
      automation_target:
        entity_id:
        - light.sconces
        - light.lamps
      on_time: '16:00:00'
      off_time: 00:00:00
      trigger_at_homeassistant_startup: true
- id: '1668213805270'
  alias: Cycle Printer Power
  description: Cycles the printer power when it goes unavailable for 5 minutes.
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.printer_ping
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 1fca000a5a84fd7fa576a5369dc85108
    entity_id: switch.printer_power
    domain: switch
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - type: turn_on
    device_id: 1fca000a5a84fd7fa576a5369dc85108
    entity_id: switch.printer_power
    domain: switch
  - service: notify.notify
    data:
      title: Printer power cycled
      message: The printer has been power cycled due to unavailability.
  mode: single
- id: '1666221462797'
  alias: Outdoor Holiday Lights Schedule
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.morning
    - binary_sensor.evening
  - platform: homeassistant
    event: start
  condition: []
  action:
  - if:
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.morning
        state: 'on'
      - condition: state
        entity_id: binary_sensor.evening
        state: 'on'
    then:
    - service: switch.turn_on
      data: {}
      target:
        entity_id:
        - switch.outdoor_holiday_lights
        - switch.outdoor_1
        - switch.outdoor_2
    else:
    - service: switch.turn_off
      data: {}
      target:
        entity_id:
        - switch.outdoor_holiday_lights
        - switch.outdoor_1
        - switch.outdoor_2
  mode: single
- id: '1666224817497'
  alias: Update notifications
  description: ''
  use_blueprint:
    path: mdegat01/update_notifications.yaml
    input:
      reminder_hours: '24'
      update_entities:
      - update.hacs_update
      - update.home_assistant_core_update
      - update.home_assistant_operating_system_update
      - update.home_assistant_supervisor_update
      mobile_app_device: 60d03d2db87a2e1e2a5f5bcce32b77aa
      only_after: 06:00:00
      only_before: '22:00:00'
      send_to_ha: true
      run_config_check: true
- id: '1671295554466'
  alias: Indoor Holiday Lights Schedule
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.indoor_holiday_lights_schedule
  - platform: homeassistant
    event: start
  condition: []
  action:
  - if:
    - condition: or
      conditions:
      - condition: state
        entity_id: schedule.indoor_holiday_lights_schedule
        state: 'on'
    then:
    - service: switch.turn_on
      data: {}
      target:
        entity_id:
        - switch.indoor_holiday_lights_group
    else:
    - service: switch.turn_off
      data: {}
      target:
        entity_id:
        - switch.indoor_holiday_lights_group
  mode: single
- id: '1673876754321'
  alias: Notify on AP move
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.david_s_iphone_14_pro
    attribute: ap_mac
  condition: []
  action:
  - service: notify.mobile_app_davids_iphone_14_pro
    data:
      title: David's phone moved
      message: 'AP: {{ state_attr(''device_tracker.david_s_iphone_14_pro'', ''ap_mac'')
        }}'
  mode: single
- id: '1673876814286'
  alias: Notify when Jacob's switch moves APs
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.nintendo_switch_jacob
    attribute: ap_mac
  condition: []
  action:
  - service: notify.mobile_app_davids_iphone_14_pro
    data:
      title: FOUND
      message: 'AP: {{ state_attr(''device_tracker.nintendo_switch_jacob'', ''ap_mac'')
        }}'
  mode: single
- id: '1673970806545'
  alias: Office unoccupied
  description: Turn off the office lamps when room is unoccupied
  trigger:
  - platform: state
    entity_id:
    - sensor.david_iphone
    - sensor.sarah_iphone
    from: office
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.office_guest
    state: 'off'
  - condition: not
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.david_iphone
        state: office
        for:
          hours: 0
          minutes: 0
          seconds: 0
      - condition: state
        entity_id: sensor.sarah_iphone
        state: office
        for:
          hours: 0
          minutes: 0
          seconds: 0
  action:
  - service: notify.mobile_app_davids_iphone_14_pro
    data:
      message: 'The office is unoccupied '
      title: Presence detection
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.office
  mode: single
- id: '1673972330662'
  alias: Office occupied
  description: Turn on the office lamps when the room is occupied.
  trigger:
  - platform: state
    entity_id:
    - sensor.david_iphone
    - sensor.sarah_iphone
    to: office
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: state
    entity_id: input_boolean.office_guest
    state: 'off'
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.office
  - service: notify.mobile_app_davids_iphone_14_pro
    data:
      message: '{{ state_attr(trigger.entity_id, ''friendly_name'') }} entered the
        office.'
      title: Presence detection
  mode: single
- id: '1674225063177'
  alias: Downstairs lights lux
  description: Turn downstairs lights on and off based on ambient brightness.
  trigger:
  - platform: state
    entity_id:
    - sensor.espresense_living_room_bh1750_lux_2
  condition:
  - condition: or
    alias: Is morning or daytime
    conditions:
    - condition: state
      entity_id: binary_sensor.morning
      state: 'on'
    - condition: state
      entity_id: binary_sensor.daytime
      state: 'on'
  - condition: template
    value_template: "{{ (as_timestamp(now()) -\n  as_timestamp(state_attr('automation.downstairs_lights_lux',
      'last_triggered') |\n  default(0)) | int) > 300\n}}"
    alias: Debounce (5m)
  action:
  - if:
    - condition: numeric_state
      entity_id: sensor.espresense_living_room_bh1750_lux
      below: input_number.living_room_lux_lower_bound
    then:
    - service: light.turn_on
      alias: Turn on lights
      data:
        transition: 5
      target:
        entity_id:
        - light.lamps
        - light.sconces
    else:
    - if:
      - condition: numeric_state
        entity_id: sensor.espresense_living_room_bh1750_lux
        above: input_number.living_room_lux_upper_bound
      then:
      - service: light.turn_off
        data:
          transition: 5
        target:
          entity_id:
          - light.lamps
          - light.sconces
  mode: single
- id: '1674225278399'
  alias: Downstairs lux high
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.espresense_living_room_bh1750_lux_2
  condition:
  - condition: or
    alias: Is morning or daytime
    conditions:
    - condition: state
      entity_id: binary_sensor.morning
      state: 'on'
    - condition: state
      entity_id: binary_sensor.daytime
      state: 'on'
  - condition: numeric_state
    alias: Brightness is above Upper Bound
    entity_id: sensor.espresense_living_room_bh1750_lux_2
    above: input_number.living_room_lux_upper_bound
  - condition: and
    conditions:
    - condition: state
      alias: Lamps are on
      entity_id: light.lamps
      state: 'on'
    - condition: state
      alias: Sconces are on
      entity_id: light.sconces
      state: 'on'
  action:
  - service: light.turn_off
    alias: Turn off lights
    data: {}
    target:
      entity_id:
      - light.lamps
      - light.sconces
  - service: notify.mobile_app_davids_iphone_14_pro
    alias: Notify David
    data:
      message: Turning off downstairs lights because it's bright.
      title: Lux change
    enabled: false
  mode: single
- id: '1677684339058'
  alias: '[TEST] Front door notification'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - lock.front_door_lock
    to: unlocked
  condition:
  - condition: state
    entity_id: lock.front_door_lock
    attribute: changed_by
    state: Changed by mobile device
  action:
  - service: notify.mobile_app_davids_iphone_14_pro
    data:
      message: Front door unlocked by mobile device
      title: Front door unlocked
  mode: single
- id: '1679071951950'
  alias: Doorbell detected person
  description: ''
  trigger:
  - platform: device
    device_id: e94f865b148d4476194fa9a57cc74f9c
    domain: nest
    type: camera_person
  condition: []
  action: []
  mode: single
- id: '1679071973766'
  alias: Doorbell pressed
  description: ''
  trigger:
  - platform: device
    device_id: e94f865b148d4476194fa9a57cc74f9c
    domain: nest
    type: doorbell_chime
  condition: []
  action: []
  mode: single
- id: '1679071985729'
  alias: Doorbell detected motion
  description: ''
  trigger:
  - platform: device
    device_id: e94f865b148d4476194fa9a57cc74f9c
    domain: nest
    type: camera_motion
  condition: []
  action: []
  mode: single
- id: '1680704667983'
  alias: Notify David when washer is done
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.washer_wash_completed
    from: 'off'
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.david
      state: home
    - condition: state
      entity_id: binary_sensor.dryer_dry_completed
      state: 'on'
  action:
  - service: notify.mobile_app_davids_iphone_14_pro
    data:
      message: Washer is done
  mode: single
- id: '1680705374664'
  alias: Notify David when dryer is done
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.dryer_dry_completed
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: person.david
    state: home
  action:
  - service: notify.mobile_app_davids_iphone_14_pro
    data:
      message: Dryer is done
  mode: single
- id: '1689686012701'
  alias: Notify on Front Porch Events
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.front_porch
      notify_device: 76657f931338cbcfa417bac484ad8cf4
      message: '{{ label }} detected - {{ camera_name }}'
      attachment: snapshot
      update_thumbnail: true
      ios_live_view: true
      zone_filter: true
      zones:
      - porch_zone
      - driveway_zone
      presence_filter: person.david
      cooldown: 60
      debug: false
- id: '1691000633447'
  alias: Toggle Notification automation based on Sarah's location
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.sarah
    from:
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: person.sarah
        state: home
      sequence:
      - service: automation.turn_off
        data:
          stop_actions: true
        target:
          entity_id: automation.notify_on_front_porch_events
    - conditions:
      - condition: state
        entity_id: person.sarah
        state: not_home
      sequence:
      - service: automation.turn_on
        data: {}
        target:
          entity_id: automation.notify_on_front_porch_events
  mode: single
- id: '1691193081488'
  alias: Notify Sarah on Front Porch activity
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.front_porch
      notify_device: 137b7007585ffc57cc04f79c7f86bf6b
      alert_once: false
      ios_live_view: true
      zone_filter: true
      zones:
      - porch_zone
      update_thumbnail: true
      debug: false
- id: '1693766230753'
  alias: Notify David when pork hits 203F
  description: ''
  trigger: []
  condition:
  - type: is_temperature
    condition: device
    device_id: 5410febb0fb5f482c60ff71e29fffc92
    entity_id: 188be0ef5ff6181d1e88fd8df36a65d0
    domain: sensor
    above: 202
  action:
  - service: notify.mobile_app_davids_iphone_14_pro
    data:
      message: Pork is done
  mode: single
