- id: letsencrypt-renewal
  alias: LetsEncrypt renewal
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: hassio.addon_stop
    data:
      addon: core_nginx_proxy
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
  - delay: 00:01:30
  - service: hassio.addon_start
    data:
      addon: core_nginx_proxy
- id: '1641092271455'
  alias: Sync Deck Lights
  description: ''
  use_blueprint:
    path: adchevrier/synchronize-the-on-off-state-of-2-entities.yaml
    input:
      entity_1: switch.deck_light
      entity_2: switch.deck_string_lights
- id: '1643764828147'
  alias: Downstairs AM/PM On-Off
  description: ''
  use_blueprint:
    path: EPMatt/on_off_schedule_state_persistence.yaml
    input:
      automation_target:
        entity_id:
        - light.foyer_lamp
        - light.corner_lamp
        - light.side_table_lamp
      on_time: 06:00:00
      off_time: '23:00:00'
      trigger_at_homeassistant_startup: true
- id: '1643764971872'
  alias: Lights On At Sunset
  description: ''
  use_blueprint:
    path: CyanAutomation/lights_on_at_sunset.yaml
    input:
      target_light:
        entity_id:
        - light.corner_lamp
        - light.foyer_lamp
        - light.side_table_lamp
- id: '1643765594758'
  alias: Lights on at Sunrise
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '0'
  condition:
  - condition: sun
    before: sunrise
    before_offset: 00:30
  action:
  - service: adaptive_lighting.apply
    data:
      entity_id: switch.adaptive_lighting_downstairs
  mode: single
