- id: letsencrypt-renewal
  alias: LetsEncrypt renewal
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: hassio.addon_stop
    data:
      addon: core_nginx_proxy
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
  - delay: 00:01:30
  - service: hassio.addon_start
    data:
      addon: core_nginx_proxy
- id: '1641092271455'
  alias: Sync Deck Lights
  description: ''
  use_blueprint:
    path: adchevrier/synchronize-the-on-off-state-of-2-entities.yaml
    input:
      entity_1: switch.deck_light
      entity_2: switch.deck_string_lights
- id: '1643764828147'
  alias: Downstairs AM time schedule
  description: ''
  use_blueprint:
    path: EPMatt/on_off_schedule_state_persistence.yaml
    input:
      automation_target:
        entity_id:
        - light.sconces
        - light.lamps
        - switch.circadian_lighting_downstairs
      on_time: 06:00:00
      off_time: 09:30:00
      trigger_at_homeassistant_startup: true
      custom_trigger_event: s
- id: '1656444036964'
  alias: Daytime Power Outage
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.generator_power_outage
    from: 'false'
    to: 'true'
  condition:
  - condition: or
    conditions:
    - condition: time
      before: '19:00:00'
      after: 08:00:00
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
    - condition: and
      conditions:
      - type: is_not_occupied
        condition: device
        device_id: fb3f16cafb19fcb4fa962d5e921c6df2
        entity_id: binary_sensor.downstairs_occupancy
        domain: binary_sensor
      - type: is_not_occupied
        condition: device
        device_id: e46e919da6b49d895b1900a7b140be90
        entity_id: binary_sensor.upstairs_occupancy
        domain: binary_sensor
      - type: is_not_occupied
        condition: device
        device_id: e52f1373f5b572bff91c6742f52b470e
        entity_id: binary_sensor.basement_occupancy
        domain: binary_sensor
      - type: is_not_occupied
        condition: device
        device_id: 216957fddab350586feab9357425ce0a
        entity_id: binary_sensor.jacobs_room_occupancy
        domain: binary_sensor
    - condition: device
      device_id: fb3f16cafb19fcb4fa962d5e921c6df2
      domain: climate
      entity_id: climate.downstairs
      type: is_preset_mode
      preset_mode: Away
    - condition: device
      device_id: e46e919da6b49d895b1900a7b140be90
      domain: climate
      entity_id: climate.upstairs
      type: is_preset_mode
      preset_mode: Away
  action:
  - device_id: fb3f16cafb19fcb4fa962d5e921c6df2
    domain: climate
    entity_id: climate.downstairs
    type: set_preset_mode
    preset_mode: Away
  - device_id: e46e919da6b49d895b1900a7b140be90
    domain: climate
    entity_id: climate.upstairs
    type: set_preset_mode
    preset_mode: Away
  mode: single
- id: '1659480564190'
  alias: Downstairs PM time schedule
  description: ''
  use_blueprint:
    path: EPMatt/on_off_schedule_state_persistence.yaml
    input:
      automation_target:
        entity_id:
        - light.sconces
        - light.lamps
        - switch.circadian_lighting_downstairs
      on_time: '18:00:00'
      off_time: '23:00:00'
      trigger_at_homeassistant_startup: true
- id: '1668213805270'
  alias: Cycle Printer Power
  description: Cycles the printer power when it goes unavailable for 5 minutes.
  trigger: []
  condition:
  - condition: state
    entity_id: sensor.canon_mf741c
    state: unavailable
    for:
      hours: 0
      minutes: 5
      seconds: 0
  action:
  - type: turn_off
    device_id: 1fca000a5a84fd7fa576a5369dc85108
    entity_id: switch.printer_power
    domain: switch
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - type: turn_on
    device_id: 1fca000a5a84fd7fa576a5369dc85108
    entity_id: switch.printer_power
    domain: switch
  - service: notify.notify
    data:
      title: Printer power cycled
      message: The printer has been power cycled due to unavailability.
  mode: single
- id: '1666221462797'
  alias: Holiday Lights Schedule
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.morning
    - binary_sensor.evening
  - platform: homeassistant
    event: start
  condition: []
  action:
  - if:
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.morning
        state: 'on'
      - condition: state
        entity_id: binary_sensor.evening
        state: 'on'
    then:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.holiday_lights
    else:
    - service: switch.turn_off
      data: {}
      target:
        entity_id: switch.holiday_lights
  mode: single
- id: '1666224817497'
  alias: Update notifications
  description: ''
  use_blueprint:
    path: mdegat01/update_notifications.yaml
    input:
      reminder_hours: None
      update_entities:
      - update.hacs_update
      - update.home_assistant_core_update
      - update.home_assistant_operating_system_update
      - update.home_assistant_supervisor_update
      mobile_app_device: 60d03d2db87a2e1e2a5f5bcce32b77aa
      only_after: 06:00:00
      only_before: '22:00:00'
