- platform: template
  sensors:
    adaptive_lighting_office_color_temp_mired:
      unit_of_measurement: "mired"
      value_template: >
        {{ state_attr("switch.adaptive_lighting_office", "color_temp_mired") }}
    adaptive_lighting_office_color_temp_kelvin:
      unit_of_measurement: "K"
      value_template: >
        {{ state_attr("switch.adaptive_lighting_office", "color_temp_kelvin") }}
    adaptive_lighting_office_brightness:
      unit_of_measurement: "%"
      value_template: >
        {{ state_attr("switch.adaptive_lighting_office", "brightness_pct") }}
    adaptive_lighting_office_sun_position:
      unit_of_measurement: "%"
      value_template: >
        {{ 100 * state_attr("switch.adaptive_lighting_office", "sun_position") }}
