title: Casa de Knowles
resources:
  - url: /local/lovelace-slider-entity-row/slider-entity-row.js
    type: js
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/homeassistant-lovelace-google-calendar-card/calendar-card.js
    type: js

views:
  - title: Home
    id: home
    icon: mdi:calendar
    badges:
      - device_tracker.davids_iphone_x
      - device_tracker.sarahsiphone
      - climate.thermostat
      - sensor.thermostat_temperature
      - sensor.thermostat_humidity
      - sensor.lyft_time
    cards:
      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.dark_sky
          - type: iframe
            url: https://maps.darksky.net/@radar,40.720,-74.047,11?marker=40.720,-74.047&marker-name=Jersey%20City
            aspect_ratio: 75%
      - type: vertical-stack
        cards:
          - type: glance
            entities:
              - binary_sensor.washer
              - binary_sensor.dryer
              - switch.holiday_lights
          - type: custom:calendar-card
            showProgressBar: false
            entities:
              - calendar.casadeknowlesgmailcom
  - title: Climate
    id: climate
    icon: mdi:thermometer
    badges:
      - sun.sun
      - sensor.yr_symbol
      - sensor.thermostat_temperature
      - sensor.kids_room_temperature
      - sensor.thermostat_humidity
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: climate.thermostat
                name: Thermostat
                secondary_info: last-changed
          - type: history-graph
            entities:
              - sensor.kids_room_temperature
              - sensor.thermostat_temperature
              - sensor.dark_sky_temperature
          - type: history-graph
            entities:
              - sensor.dark_sky_humidity
              - sensor.thermostat_humidity
  - title: House
    id: house
    icon: mdi:home-assistant
    cards:
      - type: vertical-stack
        cards:
          - type: picture-entity
            title: Downstairs
            entity: camera.entryway
            camera_image: camera.entryway
          - type: entities
            show_header_toggle: true
            entities:
              - entity: light.downstairs_hallway_lights
                name: Hallway Lights
                secondary_info: last-changed
                type: custom:slider-entity-row
              - entity: light.front_foyer_floor_lamp_and_doorbell
                name: Doorbell
                secondary_info: last-changed
      - type: vertical-stack
        title: "Jacob's Room"
        cards:
          - type: vertical-stack
            cards:
              - type: picture-entity
                title: "Jacob's Room"
                entity: camera.jacobs_room
              - type: entities
                entities:
                  - entity: switch.noisemaker
                    name: Noisemaker
                    secondary_info: last-changed
                  - entity: sensor.kids_room_temperature
                    name: Temperature
                    secondary_info: last-changed
      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - entity: light.living_room_main_lights
            name: Main Lights
            secondary_info: last-changed
            type: custom:slider-entity-row
          - entity: light.kitchen_island_pendants
            name: Island Pendants
            secondary_info: last-changed
            type: custom:slider-entity-row
          - entity: light.dining_room_chandelier
            name: Chandelier
            secondary_info: last-changed
            type: custom:slider-entity-row
          - entity: switch.living_room_ceiling_fan
            name: Ceiling Fan
            secondary_info: last-changed
      - type: history-graph
        title: Laundry
        show_header_toggle: false
        entities:
          - binary_sensor.washer
          - binary_sensor.dryer
