title: Casa de Knowles
resources:
  - url: /local/lovelace-slider-entity-row/slider-entity-row.js
    type: js
  - url: https://unpkg.com/moment@2.23.0/moment.js
    type: js
  - url: /local/homeassistant-lovelace-google-calendar-card/calendar-card.js
    type: js
  - url: /local/calendar-card/calendar-card.js?v=1.2.2
    type: module

views:
  - title: Home
    id: home
    icon: mdi:calendar
    badges:
      - device_tracker.davids_iphone_x
      - device_tracker.sarahsiphone
      - climate.thermostat
      - sensor.thermostat_temperature
      - sensor.thermostat_humidity
      - sensor.lyft_time
    cards:
      - id: c90a8aedf2c240459710978f05f892bd  # Automatically created id
        type: weather-forecast
        entity: weather.dark_sky
      - id: 558ef6db887b4e50a2400189d02140c3  # Automatically created id
        type: iframe
        url: https://maps.darksky.net/@radar,40.720,-74.047,11?marker=40.720,-74.047&marker-name=Jersey%20City
        aspect_ratio: 75%
      - id: cfdf023bdf894e7d9a62a4f7ea0325cd  # Automatically created id
        type: glance
        entities:
          - binary_sensor.washer
          - binary_sensor.dryer
          - light.front_foyer_floor_lamp_and_doorbell
          - switch.holiday_lights
      - id: 90b9dfc71cf443e991e796534d378e56  # Automatically created id
        type: custom:calendar-card
        showProgressBar: false
        entities:
          - calendar.casadeknowlesgmailcom
  - title: Climate
    id: climate
    icon: mdi:thermometer
    badges:
      - sun.sun
      - sensor.yr_symbol
      - sensor.thermostat_temperature
      - sensor.kids_room_temperature
      - sensor.thermostat_humidity
    cards:
      - id: fb85676e29c642ff83228063ed5708bb  # Automatically created id
        type: thermostat
        entity: climate.thermostat
      - id: 48a380c667fb41009c1213e84c9b7474  # Automatically created id
        type: history-graph
        entities:
          - sensor.kids_room_temperature
          - sensor.thermostat_temperature
          - sensor.dark_sky_temperature
      - id: 259cfa001033410a9d263e02e9eca2f8  # Automatically created id
        type: history-graph
        entities:
          - sensor.dark_sky_humidity
          - sensor.thermostat_humidity
  - title: House
    id: house
    icon: mdi:home-assistant
    cards:
      - id: 481fe08ae22c41c58d3ad8b7e7e65258  # Automatically created id
        type: vertical-stack
        cards:
          - type: picture-entity
            title: Downstairs
            entity: camera.entryway
            camera_image: camera.entryway
          - type: entities
            show_header_toggle: true
            entities:
              - entity: light.downstairs_hallway_lights
                name: Hallway Lights
                secondary_info: last-changed
                type: custom:slider-entity-row
              - entity: light.front_foyer_floor_lamp_and_doorbell
                name: Doorbell
                secondary_info: last-changed
      - id: f68a7728fba14001abfc4085a06f24a1  # Automatically created id
        type: vertical-stack
        title: Jacob's Room
        cards:
          - type: vertical-stack
            cards:
              - type: picture-entity
                title: Jacob's Room
                entity: camera.jacobs_room
              - type: entities
                entities:
                  - entity: switch.noisemaker
                    name: Noisemaker
                    secondary_info: last-changed
                  - entity: sensor.kids_room_temperature
                    name: Temperature
                    secondary_info: last-changed
      - id: 3ee76e86196f4c34b237b5926460372f  # Automatically created id
        type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - entity: light.living_room_main_lights
            name: Main Lights
            secondary_info: last-changed
            type: custom:slider-entity-row
          - entity: light.kitchen_island_pendants
            name: Island Pendants
            secondary_info: last-changed
            type: custom:slider-entity-row
          - entity: light.dining_room_chandelier
            name: Chandelier
            secondary_info: last-changed
            type: custom:slider-entity-row
          - entity: switch.living_room_ceiling_fan
            name: Ceiling Fan
            secondary_info: last-changed
      - id: 0bea2fc60ecc4224abee52e4b32f073f  # Automatically created id
        type: history-graph
        title: Laundry
        show_header_toggle: false
        entities:
          - binary_sensor.washer
          - binary_sensor.dryer
