title: Casa de Knowles
views:
  - title: Home
    id: home
    icon: mdi:calendar
    badges:
      - device_tracker.davids_iphone_x
      - device_tracker.sarahsiphone
      - sensor.yr_symbol
      - sensor.thermostat_temperature
      - sensor.thermostat_humidity
      - sensor.lyft_time
    cards:
      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.dark_sky
          - type: picture
            title: Radar
            image: "https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=OKX&brand=wui&num=15&delay=15&type=N0R&frame=0&scale=0.5&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=601.75&centery=185.25&transx=201.75&transy=-54.75&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=1&rand=25543743&lat=0&lon=0&label=you"
      - type: iframe
        title: Calendar
        url: "https://calendar.google.com/calendar/embed?showTitle=0&showNav=0&showDate=0&showPrint=0&showTabs=0&showCalendars=0&showTz=0&mode=AGENDA&wkst=1&src=casa.de.knowles%40gmail.com"
      - type: media-control
        entity: media_player.spotify
  - title: Climate
    id: climate
    icon: mdi:thermometer
    badges:
      - sun.sun
      - sensor.yr_symbol
      - sensor.thermostat_temperature
      - sensor.blink_foyer_temperature
      - sensor.kids_room_temperature
      - sensor.thermostat_humidity
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: climate.thermostat
                name: Thermostat
                secondary_info: last-changed
          - type: history-graph
            entities:
              - sensor.blink_foyer_temperature
              - sensor.kids_room_temperature
              - sensor.thermostat_temperature
              - sensor.dark_sky_temperature
          - type: history-graph
            entities:
              - sensor.dark_sky_humidity
              - sensor.thermostat_humidity
  - title: House
    id: house
    icon: mdi:home-assistant
    cards:
      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - entity: light.living_room_main_lights
            name: Main Lights
            secondary_info: last-changed
          - entity: light.kitchen_island_pendants
            name: Island Pendants
            secondary_info: last-changed
          - entity: light.dining_room_chandelier
            name: Chandelier
            secondary_info: last-changed
          - entity: switch.living_room_ceiling_fan
            name: Ceiling Fan
            secondary_info: last-changed
      - type: vertical-stack
        cards:
          - type: picture-entity
            title: Downstairs
            entity: camera.foyer
            camera_image: camera.foyer
          - type: entities
            show_header_toggle: true
            entities:
              - entity: light.downstairs_hallway_lights
                name: Hallway Lights
                secondary_info: last-changed
              - entity: light.front_foyer_floor_lamp_and_doorbell
                name: Doorbell
                secondary_info: last-changed
              - entity: sensor.blink_foyer_temperature
                name: Temperature
                secondary_info: last-changed
              - entity: sensor.blink_foyer_battery
      - type: vertical-stack
        title: "Jacob's Room"
        cards:
          - type: vertical-stack
            cards:
              - type: picture-entity
                title: "Jacob's Room"
                entity: camera.jacobs_room
              - type: entities
                entities:
                  - entity: switch.jacob_noisemaker
                    name: Noisemaker
                    secondary_info: last-changed
                  - entity: sensor.kids_room_temperature
                    name: Temperature
                    secondary_info: last-changed
