esphome:
  name: "door-chime"
  name_add_mac_suffix: false
  friendly_name: Door Chime

  on_boot:
    then:
      - logger.log: "i am boot"
      - dfplayer.set_volume: 30

esp32:
  board: esp32dev
  framework:
    type: arduino
    # type: esp-idf

# Enable logging
logger:
  level: DEBUG

api:
  encryption:
    key: W6NBhSDjHcQpec8NuNGKyzvsWBeEKYz1xJL3gG+OU0Q=

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

uart:
  id: uart_dfplayer
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  debug:

dfplayer:
  uart_id: uart_dfplayer
  on_finished_playback: 
    then:
      - logger.log: "Playback finished"

mqtt:
  broker: 192.168.1.11
  username: hass
  password: mosquitto
  on_connect:
    then:
      - logger.log: "MQTT connected"
  on_message:
    - topic: "rtl_433/9b13b3f4-rtl433/devices/DSC-Security/+/closed"
      payload: "0"
      then:
        - logger.log: "Some door opened"
        - dfplayer.play_mp3: 
            file: 1
    # - topic: "rtl_433/9b13b3f4-rtl433/devices/DSC-Security/2959527/closed"
    #   payload: "0"
    #   then:
    #     - logger.log: "Back door opened"
    #     - dfplayer.play_mp3: 1
