homeassistant:
  enabled: true
advanced:
  network_key:
    - 30
    - 168
    - 187
    - 105
    - 233
    - 227
    - 63
    - 19
    - 177
    - 75
    - 206
    - 76
    - 139
    - 164
    - 76
    - 145
  pan_id: 14104
  ext_pan_id:
    - 119
    - 23
    - 39
    - 159
    - 16
    - 183
    - 61
    - 3
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  last_seen: ISO_8601
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: eeheephai1Pun0eoshuoPah6doo4ootongoalooyo5AveeDohpi7Baevohchoodo
frontend:
  enabled: true
  port: 8099
serial:
  port: /dev/ttyUSB0
device_options: {}
devices:
  '0x00158d0009eef81e':
    friendly_name: Office Button
  '0x0cae5ffffe899d86':
    friendly_name: Office Blackout Shade
    invert_cover: false
  '0x0cae5ffffe89a007':
    friendly_name: Office Privacy Shade
    invert_cover: false
  '0x0cae5ffffe89801c':
    friendly_name: Sarah Privacy Shade
    invert_cover: false
  '0x0cae5ffffe89a378':
    friendly_name: Sarah Blackout Shade
    invert_cover: false
  '0x0cae5ffffe89a165':
    friendly_name: David Privacy Shade
    invert_cover: false
  '0x0cae5ffffe89a005':
    friendly_name: David Blackout Shade
    invert_cover: false
  '0x0cae5ffffe89b0b6':
    friendly_name: Primary Bedroom Privacy Shade
    invert_cover: false
  '0x0cae5ffffe899d83':
    friendly_name: Primary Bedroom Blackout Shade
    invert_cover: false
  '0x0cae5ffffe8980be':
    friendly_name: Jacob Privacy Shade
    invert_cover: false
  '0x0cae5ffffe89a009':
    friendly_name: Jacob Blackout Shade
    invert_cover: false
  '0x0cae5ffffe89a003':
    friendly_name: Guest Bedroom Privacy Shade
    invert_cover: false
  '0x0cae5ffffe89a167':
    friendly_name: Guest Bedroom Blackout Shade
    invert_cover: false
  '0x6cfd22fffe429e71':
    friendly_name: Living Room Zigbee Repeater
  '0x6cfd22fffe42aae9':
    friendly_name: Jacob's Room Zigbee Repeater
  '0x6cfd22fffe40e941':
    friendly_name: Primary Bedroom Zigbee Repeater
  '0x0ceff6fffe78d817':
    friendly_name: Primary Bedroom Sensor
  '0x6cfd22fffee7a08d':
    friendly_name: Dining Room Front Privacy Shade
    invert_cover: true
    cover_position_tilt_disable_report: false
  '0x6cfd22fffee7ac03':
    friendly_name: Living Room Left Privacy Shade
    invert_cover: true
  '0x4c97a1fffe560c06':
    friendly_name: Living Room Right Privacy Shade
    invert_cover: true
  '0x6cfd22fffee7ac15':
    friendly_name: Dining Room Side Privacy Shade
    invert_cover: true
  '0x6cfd22fffee7a093':
    friendly_name: Sitting Room Privacy Shade
    invert_cover: true
  '0x4c97a1fffe560bde':
    friendly_name: Living Room Center Privacy Shade
    invert_cover: true
  '0x4c97a1fffe560243':
    friendly_name: Kitchen Privacy Shade
    invert_cover: true
  '0x0ceff6fffeee717f':
    friendly_name: Jacob Sensor
  '0x00124b002fa14bfa':
    friendly_name: Jacob Plug
groups:
  '1':
    friendly_name: primary_bedroom_blackout_shades
availability:
  enabled: true
  active:
    timeout: 5
  passive:
    timeout: 1500
version: 4
